### PR TITLE
[FE] Add homepage navbar

### PR DESCRIPTION
**Pull request by stonefruit**
Add a basic navbar for homepage

Screenshot 2021-12-17 at 2 52 17 PM

### CODE REVIEW

**Comment by ryhuz** [comment]
not necessarily a recommended change for this PR, but will we have the top nav bar navigation buttons/menu?

**Comment by stonefruit** [comment]
> not necessarily a recommended change for this PR, but will we have the top nav bar navigation buttons/menu?
> 
> also. just noting a TODO, there's responsiveness issue which i think is due to the image sections

We can add nav buttons in the future if that is what is needed. For now it is there so it isn't a black bar.

Is the responsiveness issue from the rest of the page or the nav bar?

**Comment by ryhuz** [comment]
the responsiveness affects the page and the nav bar. i suspect when we work out the flexing in mobile view, it will solve itself

**Comment by stonefruit** [comment]
> the responsiveness affects the page and the nav bar. i suspect when we work out the flexing in mobile view, it will solve itself

Is the current direction mobile first? if not then i guess we can sort it out when we get there.

**Comment by ryhuz** [comment]
> > the responsiveness affects the page and the nav bar. i suspect when we work out the flexing in mobile view, it will solve itself
> 
> Is the current direction mobile first? if not then i guess we can sort it out when we get there.

I don't think it's ever been mentioned, but i assume web first

**Comment by stonefruit** [comment]
> > > the responsiveness affects the page and the nav bar. i suspect when we work out the flexing in mobile view, it will solve itself
> > 
> > Is the current direction mobile first? if not then i guess we can sort it out when we get there.
> 
> I don't think it's ever been mentioned, but i assume web first

OK. So would there anything to be changed for this PR to be approved?

**Review by ryhuz — APPROVED** [review]

**Pull request merged**
